In [167]:
import numpy as np

my_array = np.array(1000000)   #넘파이에 1000000개짜리 리스트를 만들어줘
my_list = list(range(1000000))


In [7]:
# array와 list 비교하기
%timeit my_list2 = [i*2 for i in my_list]   #list comprehension
%timeit my_array2 = my_array * 2

49.6 ms ± 976 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.06 μs ± 23.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
]
data = np.array(a)
print(data)  #리스트에 소수가 포함되어 있으면, 정수도 소수로 바꿔서 형태를 맞춰줌

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [11]:
# 0차원 : 스칼라(scalar), 1차원 : 벡터(vector), 
# 2차원 : 행렬(matrix), 3차원: 텐서(tensor)
print(data * 10)  
print(data + data) #똑같은 위치에 있는 애들끼리 더해줌

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [15]:
print(data.shape) #(가장 바깥에 있는 배열 개수, 배열 안에 있는 데이터 개수)
# (2,3) = 2행 3열
print(data.dtype) # 안에 있는 데이터 유형을 말해준다

(2, 3)
float64


In [152]:
b = [
    [[1, 2, 3],[4, 5, 6],[7, 8, 9]],
    [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
]
data_2 = np.array(b)
print(data_2.shape)

(2, 3, 3)


# ndarray 생성하기
- np.array()
- np.ndim
- np.shape

In [20]:
#리스트를 array형태로 바꾸기

data1 = [1,2,3,4,5]
arr1  = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [23]:
arr2 = np.array([[1.1, 2.2],[3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [26]:
#차원

print(arr1.ndim)
print(arr2.ndim)

1
2


In [27]:
# 데이터의 구조

print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [73]:
#데이터 구조 파악하기

print(np.zeros(10)) 
print([0]*10)  #파이썬
print(np.zeros(  (5,5)  ))   
print(np.empty((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[4.67296746e-307 1.69121096e-306]
  [9.45694586e-308 1.42413555e-306]]

 [[1.78019082e-306 1.37959740e-306]
  [6.23057349e-307 1.42419530e-306]]]


In [74]:
print(np.empty((2,2,2)))

[[[4.67296746e-307 1.69121096e-306]
  [9.45694586e-308 1.42413555e-306]]

 [[1.78019082e-306 1.37959740e-306]
  [6.23057349e-307 1.42419530e-306]]]


In [41]:
print(np.arange(10))  #0부터 9까지 배열 만들기

[0 1 2 3 4 5 6 7 8 9]


# ndarray 자료형

In [45]:
#형변환

arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)

print(arr1.dtype)  #정수형태
print(arr2.dtype)  #정수형태

float64
int32


In [49]:
# 형변환 2

arr1 = np.array([1,2,3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1) #소수로 바뀜
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [54]:
arr2 = np.array([1.1,2.2,3.3])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64) # 정수형으로 바꿀 때 소수점 뒤는 버림
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3]
int64


## 산술 연산

In [63]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr * arr) #같은 위치에 있는 값끼리 곱한다
print(arr + arr)
print(1 / arr)
print(arr ** 3) # 세제곱

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [72]:
#크기 비교하기

arr2 = np.array([[3,2,1],[1,2,3]])
print(arr)
print(arr2)
print(arr > arr2) # 같은 위치에 있는 데이터 크기비교
print(arr == 3) #데이터가 3인 애만 True표시

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인과 슬라이싱

In [80]:
arr = np.arange(10)

In [81]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [82]:
print(arr[7])
print(arr[2:5])

7
[2 3 4]


In [85]:
arr[2:5] = 10 #파이썬에는 없는 문법
print(arr)  #2번째부터 4번째 데이터가 10이된다

[ 0  1 10 10 10  5  6  7  8  9]


In [86]:
py_list = [1,2,3,4,5]
py_list[2:3].pop()
print(py_list) # 파이썬에서는 원본이 변하지 않음

[1, 2, 3, 4, 5]


In [88]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr) #2행 3열

[[1 2 3]
 [4 5 6]]


In [91]:
print(arr[1][1])  # 5에접근하는 방법
print(arr[1,1])

5
5


In [168]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
          
          [[11,12,13],[14,15,16],[17,18,19]],
          
          [[11,22,33],[44,55,66],[77,88,99]]])

In [171]:
arr3d[1,:2, 2]

array([13, 16])

In [96]:
print(arr3d.shape)

(3, 3, 3)


In [100]:
print(arr3d[2][0][1])
print(arr3d[2,0,1])

22
22


In [106]:
print(arr3d[:1, 1:, 2:])
print(arr3d[0, 1:, 2:]) # 인덱싱으로 접근하면 차원이 하나 줄어든다

[[[6]
  [9]]]
[[6]
 [9]]


In [107]:
arr3d[0, 1:, 2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


## 불리언 값으로 선택

In [109]:
names = np.array(['hong','kim','hong','kim'])
data = np.array([['math', 60],['math', 90],['eng', 70],['eng', 50]])

In [110]:
names == 'hong' 

array([ True, False,  True, False])

In [112]:
# data[[True, False, True, False]]

data[names == 'hong'] #True 위치에 있는 데이터만 불러온다
#특정 조건에 맞는 데이터를 고를 때

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [154]:
print(data[names == 'hong',1])
print(data[names == 'hong', :1])

['60' '70']
[['math']
 ['eng']]


In [117]:
print(names != 'hong')
print(~(names == 'hong')) #계산 결과의 역을 취해줌

[False  True False  True]
[False  True False  True]


In [118]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인  (fancy indexing)

In [121]:
arr = np.zeros((8,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [122]:
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [124]:
arr[[4,3,0,5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [126]:
arr[[-3,-5,-1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [134]:
arr = np.arange(32).reshape(8,4)  #행렬의 shape을 변형할 때
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [136]:
arr[[1,5],[2,3]]   #=> arr[1,2], arr[5,3] 이 선택됨

array([ 6, 23])

In [139]:
arr[[1,5]][:,[2,3]]

array([[ 6,  7],
       [22, 23]])

## 배열 전치

In [144]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [143]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [149]:
# 행렬의 곱 (내적)
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [156]:
samples = np.random.standard_normal(size = (3,3))
print(samples)

[[ 0.61186327 -0.06176759 -0.28646565]
 [-0.43438008  0.32843473  1.02328927]
 [-0.98342744  0.75188712 -1.07683767]]


In [160]:
arr1 = np.sqrt(samples)
print(arr1)# 음수를 sqrt하면 nan(결측치)출력

[[0.7822169         nan        nan]
 [       nan 0.57309225 1.01157761]
 [       nan 0.86711425        nan]]


C:\Users\1-15\AppData\Local\Temp\ipykernel_13532\2691094134.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [162]:
arr2 = np.abs(samples) #절대값
print(arr2)

[[0.61186327 0.06176759 0.28646565]
 [0.43438008 0.32843473 1.02328927]
 [0.98342744 0.75188712 1.07683767]]


In [163]:
np.isnan(arr1)

array([[False,  True,  True],
       [ True, False, False],
       [ True, False,  True]])