# 1. array 만들기
- np.array() : np.array() 괄호 안에 리스트를 넣어서 생성 **배열 선언할때는 꼭 괄호를 넣는다**
- np.ndim : 배열의 차원을 출력
- np.shape : 배열이 몇 행 몇 열인지 튜플형태로 반환 (가장 바깥에 있는 배열 개수, 배열 안에 있는 데이터 개수) 

### 1-1. np.array() - 리스트로 배열 만들기

In [9]:
import numpy as np 
my_list = [1,2,3]  #타입이 list
my_arr = np.array([1,2,3]) # 타입이 numpy.ndarray

### 1-2. np.ndim,  np.shape -데이터 구조

In [11]:
a = [
    [1, 2, 3],
    [4, 5, 6]
]
arr_a = np.array(a)
print(arr_a.ndim) # 2 : 2차원
print(arr_a.shape)  # (2, 3) : 가장 바깥에 있는 배열개수 = 2, 배열 안 데이터 개수 = 3

2
(2, 3)


In [14]:
b = [
    [[1,2],[5,6],[9,10]],
    [[3,4],[7,8],[11,12]],
    [[1,2],[2,3],[4,5]],
    [[1,1],[2,2],[3,3]]
]
arr_b = np.array(b)
print(arr_b.ndim) # 3차원
print(arr_b.shape) # (4, 3, 2) :가장 바깥에 있는 배열 개수 = 4, 그 안에 있는 뱅려 개수 = 3, 데이터 개수 =2

3
(4, 3, 2)


### 1-3 array와 list 비교하기
- print(my_list * 2)  => [1,2,3,1,2,3]
- print(my_arr * 2) => [2, 4, 6]

In [33]:
print(my_list * 2)  
print(my_arr * 2) 
my_list2 = [i * 2 for i in my_list]  # 리스트에서 이렇게 계산하는 것과 같다
print(my_list2)

[1, 2, 3, 1, 2, 3]
[2 4 6]
[2, 4, 6]


# 2. array 생성 함수
- np.arange()
- np.zeros(shape) :0으로 채워진 배열 생성
- np.empty(shape) :초기화된 값으로 배열 생성

### 2-1 np.arange()

In [19]:
print(np.arange(10)) # [0 1 2 3 4 5 6 7 8 9] : 0부터 9까지 배열 만들기
print(np.arange(0, 5, 2))  # [0 2 4] : 0 부터 4까지 2간격으로 배열 만들기

[0 1 2 3 4 5 6 7 8 9]
[0 2 4]


### 2-2 np.zeros(), np.empty()


In [22]:
print(np.zeros(3)) # [0. 0. 0.]
print(np.zeros((4,5)))
# [[0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]]
print(np.zeros((3,2,1)))
# [[[0.]
#   [0.]]

#  [[0.]
#   [0.]]

#  [[0.]
#   [0.]]]

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]]


In [23]:
print(np.empty((2, 2)))

[[0.0e+000 1.5e-323]
 [3.0e-323 4.4e-323]]


# 3. dtype() : 데이터 타입
- np.dtype()
- np.astype()

### 3-1 np.dtype() : 데이터 타입 확인

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1.1, 2.2, 3.3])
print(arr1.dtype)  #int64 : 정수형 데이터 
print(arr2.dtype)  #float64 : 실수형 데이터

int64
float64


### 3-2 astype() : 형변환

In [29]:
float_arr1 = arr1.astype(np.float64) # [1, 2, 3] = > [1. 2. 3.] :실수형으로 변환
int_arr2 = arr2.astype(np.int64) # [1.1, 2.2, 3.3] => [1 2 3] :정수형으로 변환, 소수점 아래는 버리기
print(float_arr1)
print(int_arr2)

[1. 2. 3.]
[1 2 3]


# 4. 산술연산 
- 같은 위치에 있는 값끼리 계산해준다

In [37]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr + arr)
print(arr * arr)
print(arr / arr)
print(arr - arr)
print(arr ** 3)

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]
[[  1   8  27]
 [ 64 125 216]]


### 4-1. 크기 비교하기

In [39]:
arr = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[4,5,6],[1,2,3]])
print(arr > arr2) # arr > arr2 이면 True를 반환해준다

[[False False False]
 [ True  True  True]]


# 5. 색인과 슬라이싱

In [40]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
          
          [[11,12,13],[14,15,16],[17,18,19]],
          
          [[11,22,33],[44,55,66],[77,88,99]]])

In [42]:
# 색인을 통해 17 에 접근하기
print(arr3d[1][2][0])
print(arr3d[1,2,0])

17
17


In [46]:
# 슬라이싱해서 33, 66 구하기
print(arr3d[2, :2, 2]) 
# 슬라이싱해서 5, 8, 15, 18 구하기
print(arr3d[:2, 1:, 1])

[33 66]
[[ 5  8]
 [15 18]]


In [47]:
# 슬라이싱해서 16, 19 를 10 으로 바꾸기
arr3d[1, 1:, 2] = 10
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 10]
  [17 18 10]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]


# 6. 불리언 값으로 선택하기

In [48]:
names = np.array(['hong','kim','lee','hong','lee'])
data = np.array([['math', 90],['eng', 100],['math', 99], ['eng', 70], ['eng',100]])

In [50]:
names == 'lee' #array([False, False,  True, False,  True])
data[names == 'lee'] #data([False, False,  True, False,  True])

array([['math', '99'],
       ['eng', '100']], dtype='<U21')

In [57]:
print(data[names=='lee'][0]) #['math' '99']
print(data[names=='lee', 1]) #['99','100']
print(data[names=='lee', :1]) #[['math'] ['eng']]

['math' '99']
['99' '100']
[['math']
 ['eng']]
